title: Jose Alfaro # your name (or website title) here
logo: "/images/me2.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello and welcome to my personal website. Here I display some of my previous work involving data science and statistics.
  Second description 
  <br><br>
  LinkedIn: https://www.linkedin.com/in/jose-f-alfaro/
  <br><br>
  Email: Jose.Alfaro@UTDallas.edu
  <br><br>
  <a href="https://www.linkedin.com/in/jose-f-alfaro/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
